### ISSUE TITLE
New options are semi-ineffective with pipes.

### ISSUE THREAD

**Issue by snowboundmage2** [SmartFoundations/SmartIssueTracker#78]
Extending a vanilla machine with auto-connect makes all "To Machine" pipes a lower level despite settings being "Auto: Max Unlocked". Belts work fine from what I've seen.

Settings:
![image](https://user-images.githubusercontent.com/85192202/187362535-5cdc1f9a-da8e-48be-98ec-7aba3234546b.png)
Normal refinery being placed:
![image](https://user-images.githubusercontent.com/85192202/187362703-0ec43372-39ca-4c14-bcb6-5a29e4e9dda4.png)
Pipe autoconnecting, wrong level.
![image](https://user-images.githubusercontent.com/85192202/187362766-5c9685cd-5ab1-4ad4-aad5-1e35ff61a6e5.png)
What it looks like after being finished:
![image](https://user-images.githubusercontent.com/85192202/187362863-f4191f5c-dfbb-4528-91c5-c99816efd157.png)
Preparing for extension("main" pipe correct level, "to machine" pipe incorrect level, belts normal):
![image](https://user-images.githubusercontent.com/85192202/187362905-f1cda185-a23e-470d-94ad-1e1f7d11a124.png)

Manually placed "to machine" pipe changes to lower level pipe when extending.
![image](https://user-images.githubusercontent.com/85192202/187363349-7212f619-d48b-4b95-b168-edd9edc4125c.png)

Autoconnected "to machine" pipe is wrong level, but extended "Main" pipe is correct level.
![image](https://user-images.githubusercontent.com/85192202/187363602-52fe50cc-21f2-460b-92c2-77145541dbe5.png)

 - Game Branch: Experimental
 - Game Type: Steam
 - Game Version: 
![image](https://user-images.githubusercontent.com/85192202/187363079-f5368609-cbe1-48cd-a507-4978a356893c.png)
 - Mod Type: SMM
 - Mod Version: ![image](https://user-images.githubusercontent.com/85192202/187361729-ecbec1ed-d365-4110-8b8e-aa4e2b813aa0.png)
 - SMM/SML Version: 
![image](https://user-images.githubusercontent.com/85192202/187363700-5606f8e2-c238-4f39-88af-626a2fd1124c.png)
![image](https://user-images.githubusercontent.com/85192202/187363660-3667ef59-2703-443b-8ca9-e213f795f4e0.png)
 - Is this in multiplayer (non-private session)? Nope, Single-player/Private.
 - What other mods are you using?
![image](https://user-images.githubusercontent.com/85192202/187361512-d05dbb61-fa61-462b-9cc8-1ae0785eadeb.png)

**Comment by snowboundmage2** [comment]
Alright, part 2:
![image](https://user-images.githubusercontent.com/85192202/187364862-c2810d04-e6bb-485e-953e-f635599bbc43.png)
"To machine" based on recipe(no recipe, selects max):
![image](https://user-images.githubusercontent.com/85192202/187364989-6e29b06e-2f51-47af-aa1e-d0547be335c1.png)

Recipe selected:
![image](https://user-images.githubusercontent.com/85192202/187365151-460a3943-d495-4bac-914b-e27dc530e740.png)
Recipe for reference(40 to pipe, 20 to belt):
![image](https://user-images.githubusercontent.com/85192202/187365096-ccf33332-eea6-4553-884e-77970ea0885f.png)
Extended machine(with recipe) still goes for max on "to machine" pipe, and belt:
![image](https://user-images.githubusercontent.com/85192202/187365248-2f4c4fe8-b3c0-4c6c-8cba-ef30b3ba4a5d.png)

**Comment by snowboundmage2** [comment]
Inputs are okay for belts, not for pipes
![image](https://user-images.githubusercontent.com/85192202/187365869-7938eccc-ab04-4c87-80b2-edcdeedd1e38.png)
![image](https://user-images.githubusercontent.com/85192202/187365982-3ff2fcdc-e447-49ee-9cb3-5272ef8c51c5.png)
![image](https://user-images.githubusercontent.com/85192202/187366049-e0c2394f-f0a4-4001-b36a-5f0f8a7226bb.png)

**Comment by snowboundmage2** [comment]
Manually setting things works
![image](https://user-images.githubusercontent.com/85192202/187366379-6e9f0c78-787d-4803-9713-8b9845368733.png)
![image](https://user-images.githubusercontent.com/85192202/187366541-ae457a58-0990-4526-89b2-1501da7dae6b.png)
The belts and pipes are correct tiers.
![image](https://user-images.githubusercontent.com/85192202/187366569-46d7774b-3435-48f5-8540-1c207bda1ed9.png)

**Comment by SmartFoundations** [comment]
@snowboundmage2  so the only problem with the logic was that the pipes were not working automatically based on recipe, right? I fixed that in 19.4.407-test

**Comment by snowboundmage2** [comment]
Smart 19.4.449-test
Original problem persists("to machine" pipes aren't placing at max level)
![image](https://user-images.githubusercontent.com/85192202/187594670-d3b73dfa-ee9c-4aeb-907e-c9c90398dc58.png)
![image](https://user-images.githubusercontent.com/85192202/187594707-d0ca077d-111c-45d6-a1f2-8715a507fd7f.png)

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/77

Please follow up there.
